---
title: "기말고사"
author: "남윤주"
date: '2022-05-30'
output:
   html_document: 
    toc: yes
    toc_depth: 3
    toc_float: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=F}
install.packages("jstable")
install.packages("data.table")
library(jstable);library(data.table)
install.packages("survival")
install.packages("jskm")
```

## Table 1 만들기
아래처럼 데이터 읽은후, Q로 시작하는 변수를 범주형으로 바꾼 후 ,연도별 기술통계량을 Table로 나타내어라("jstable:CreateTableOneJS"이용)
```{r}
a <- fread("https://raw.githubusercontent.com/jinseob2kim/lecture-snuhlab/master/data/example_g1e.csv")
vars.factor <- grep("Q_", names(a), value = T)

for (v in vars.factor) {
  a[[v]] <- factor(a[[v]])
}

vars.tb1 <- names(a)[-c(1:3)]

tb1 <- CreateTableOneJS(vars = vars.tb1, strata= "EXMD_BZ_YYYY", data = a)

knitr::kable(tb1$table, caption=tb1$caption)

install.packages("DT")
library(DT)
DT::datatable(tb1$table, caption = tb1$caption)
```

## 회귀분석

### 선형회귀 분석
Time ~ rx + age + sex 선형회귀 실행 후 Table로 나타내어라
```{r}
library(survival)
# colon
res.reg <- glm(time~rx + age + sex, data = colon)
tb.reg <- jstable::glmshow.display(res.reg)
knitr::kable(tb.reg$table, caption = tb.reg$first.line)
```

### 로지스틱
status ~ rx + age + sex 로지스틱회귀 실행 후 Table로 나타내어라
```{r}
res.logistic <- glm(status~rx + age + sex, data = colon, family = binomial)
tb.logistic <- jstable::glmshow.display(res.logistic)
knitr::kable(tb.logistic$table, caption = res.logistic$first.line)
```

### 생존분석

#### Cox
Surv(time, status) ~ rx + age + sex 실행 후 Table로 나타내어라 
```{r}
res.cox <- coxph(Surv(time, status) ~ rx + age + sex, data = colon, model = T)
tb.cox <- jstable::cox2.display(res.cox)
knitr::kable(tb.cox$table, caption = tb.cox$caption)
```

## kaplan-me1er
Surv(time, status) ~ rx 실행 후 그림으로 나타내어라 
```{r}
library(jskm)
res.km <- survfit(Surv(time, status)~rx, data = colon)
jskm::jskm(res.km)
```






